# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.csproj'
  buildConfiguration: 'Debug'
  workingDirectory: 'CostumeInventory'

steps:
- task: Npm@1
  inputs:
    workingDir: '$(workingDirectory)'
    command: 'install'

- task: Npm@1
  inputs:
    workingDir: '$(workingDirectory)'
    command: 'custom'
    customCommand: 'run build'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'